# Generated by Django 3.0.3 on 2020-02-16 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='undefined', max_length=255)),
                ('resource_id', models.IntegerField(unique=True)),
                ('rating', models.FloatField(default=5)),
                ('views', models.IntegerField(default=0)),
                ('raters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='document_id',
            new_name='resource_id',
        ),
        migrations.DeleteModel(
            name='DocumentStatistics',
        ),
    ]
