# Generated by Django 3.0.3 on 2020-02-16 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20200216_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='resourcestatistics',
            options={'verbose_name_plural': 'Resource statistics'},
        ),
        migrations.RemoveField(
            model_name='resourcestatistics',
            name='raters',
        ),
        migrations.RemoveField(
            model_name='resourcestatistics',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='resourcestatistics',
            name='title',
        ),
        migrations.AddField(
            model_name='resourcestatistics',
            name='downvoters',
            field=models.ManyToManyField(related_name='downvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcestatistics',
            name='upvoters',
            field=models.ManyToManyField(related_name='upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
