# Generated by Django 3.0.3 on 2020-02-18 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20200216_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceStatistics',
            new_name='QuizStatistics',
        ),
    ]
