# Generated by Django 3.0.3 on 2020-02-18 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20200218_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizstatistics',
            options={'verbose_name_plural': 'Quiz statistics'},
        ),
        migrations.RemoveField(
            model_name='quizstatistics',
            name='resource_id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='stats',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizStatistics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizstatistics',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizstatistics',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
