# Generated by Django 3.0.3 on 2020-02-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200215_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='profilestatistics',
            name='documents_rated',
        ),
        migrations.RemoveField(
            model_name='profilestatistics',
            name='documents_read',
        ),
        migrations.RemoveField(
            model_name='profilestatistics',
            name='points',
        ),
        migrations.RemoveField(
            model_name='profilestatistics',
            name='quizzes_played',
        ),
    ]
